In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np
import webbrowser
from ipywidgets import interact
import sympy as sp

In [3]:
df_tmp=pd.read_html('https://tw.stock.yahoo.com/s/list.php?c=%AF%BC%C2%B4&rr=0.06800300%201574165733',encoding='big5')

In [4]:
df_tmp[2]

,選擇,股票代號,時間,成交,買進,賣出,漲跌,張數,昨收,開盤,最高,最低
0,NaN,1402 遠東新,14:30,30.05,30.00,30.05,△0.20,7572,29.85,29.65,30.15,29.60
1,NaN,1409 新纖,14:30,12.00,12.00,12.05,△0.15,4067,11.85,11.85,12.05,11.80
2,NaN,1410 南染,13:30,29.80,29.40,29.85,△0.30,25,29.50,29.50,29.80,29.35
3,NaN,1413 宏洲,13:30,9.92,9.85,9.92,△0.02,152,9.90,9.89,9.94,9.80
4,NaN,1414 東和,13:14,7.05,7.05,7.10,▽0.01,103,7.06,7.06,7.09,7.05
5,NaN,1416 廣豐,13:20,13.65,13.60,13.65,△0.05,32,13.60,13.60,13.65,13.60
6,NaN,1417 嘉裕,13:30,10.00,10.00,10.05,△0.03,1125,9.97,10.00,10.10,9.96
7,NaN,1418 東華,12:18,5.80,5.82,6.19,▽0.20,1,6.00,5.80,5.80,5.80
8,NaN,1419 新紡,13:30,41.75,41.70,42.00,▽0.20,4,41.95,41.95,41.95,41.65
9,NaN,1423 利華,13:30,10.30,10.30,10.35,0.00,298,10.30,10.30,10.35,10.30
10,NaN,1434 福懋,14:30,34.00,34.00,34.05,△0.15,1075,33.85,33.90,34.25,33.90
11,NaN,1439 中和,13:30,30.00,30.00,30.10,△1.80,576,28.20,28.55,30.90,28.50
12,NaN,1440 南紡,13:30,10.75,10.75,10.80,0.00,900,10.75,10.80,10.85,10.75
13,NaN,1441 大東,14:30,8.19,8.19,8.24,▽0.13,126,8.32,8.31,8.32,8.18
14,NaN,1443 立益,12:51,9.70,9.67,9.75,△0.01,39,9.69,9.69,9.70,9.65
15,NaN,1444 力麗,13:30,9.33,9.33,9.35,▽0.04,460,9.37,9.37,9.39,9.33
16,NaN,1445 大宇,13:30,6.94,6.90,6.94,▽0.02,349,6.96,6.98,6.98,6.90
17,NaN,1446 宏和,13:30,34.45,34.35,34.45,▽0.05,68,34.50,34.50,34.50,34.25
18,NaN,1447 力鵬,13:30,6.80,6.80,6.82,▽0.01,281,6.81,6.81,6.86,6.80
19,NaN,1449 佳和,13:30,7.80,7.80,7.83,▽0.18,651,7.98,7.95,8.00,7.75
20,NaN,1451 年興,13:30,21.55,21.55,21.60,▽0.05,234,21.60,21.60,21.65,21.45
21,NaN,1452 宏益,13:23,18.20,18.15,18.20,0.00,90,18.20,18.20,18.25,18.20
22,NaN,1453 大將,13:30,8.33,8.23,8.33,△0.08,56,8.25,8.18,8.34,8.18
23,NaN,1454 台富,10:53,7.89,7.81,7.87,△0.05,64,7.84,7.66,7.89,7.66
24,NaN,1455 集盛,13:30,7.80,7.80,7.81,0.00,349,7.80,7.84,7.84,7.79
25,NaN,1456 怡華,13:30,11.65,11.60,11.70,0.00,288,11.65,11.65,11.70,11.45
26,NaN,1457 宜進,13:30,13.95,13.95,14.00,0.00,338,13.95,13.90,14.10,13.90
27,NaN,1459 聯發,13:30,6.83,6.83,6.85,0.00,30,6.83,6.83,6.83,6.83
28,NaN,1460 宏遠,14:30,9.36,9.36,9.38,△0.07,645,9.29,9.29,9.44,9.29
29,NaN,1463 強盛,13:30,12.95,12.90,12.95,△0.05,57,12.90,12.90,12.95,12.85
30,NaN,1464 得力,14:30,27.00,26.95,27.05,▽0.10,2026,27.10,27.05,27.10,26.80
31,NaN,1465 偉全,13:04,14.55,14.40,14.60,△0.05,21,14.50,14.35,14.55,14.35
32,NaN,1466 聚隆,13:30,7.62,7.62,7.65,▽0.14,24,7.76,7.64,7.67,7.61
33,NaN,1467 南緯,13:30,8.42,8.42,8.44,△0.01,126,8.41,8.45,8.45,8.41
34,NaN,1468 昶和,12:47,10.10,9.95,10.10,0.00,13,10.10,10.05,10.10,9.91
35,NaN,1470 大統新創,-,-,20.90,21.30,-,-,21.30,-,-,-
36,NaN,1472 三洋紡,13:30,30.80,30.80,30.90,▽0.20,22,31.00,30.95,30.95,30.50
37,NaN,1473 台南,13:30,23.45,23.45,23.50,▽0.10,90,23.55,23.55,23.55,23.45
38,NaN,1474 弘裕,13:30,8.93,8.90,8.93,△0.01,49,8.92,8.96,8.96,8.90
39,NaN,1475 本盟,-,-,4.74,5.15,-,-,5.05,-,-,-
40,NaN,1476 儒鴻,13:30,401.5,401.50,402.00,△1.5,245,400.00,397.0,402.0,397.0
41,NaN,1477 聚陽,14:30,150.0,150.00,150.50,△0.5,2065,149.50,150.0,152.0,149.5
42,NaN,4414 如興,13:30,11.25,11.20,11.25,▽0.10,591,11.35,11.30,11.35,11.15
43,NaN,4426 利勤,14:30,50.2,50.20,50.30,▽0.4,649,50.60,50.6,51.3,49.5
44,NaN,4438 廣越,14:30,143.0,142.50,143.00,▽1.0,226,144.00,144.0,145.0,142.5

In [5]:
df_tmp[2].head()

,選擇,股票代號,時間,成交,買進,賣出,漲跌,張數,昨收,開盤,最高,最低
0,NaN,1402 遠東新,14:30,30.05,30.00,30.05,△0.20,7572,29.85,29.65,30.15,29.60
1,NaN,1409 新纖,14:30,12.00,12.00,12.05,△0.15,4067,11.85,11.85,12.05,11.80
2,NaN,1410 南染,13:30,29.80,29.40,29.85,△0.30,25,29.50,29.50,29.80,29.35
3,NaN,1413 宏洲,13:30,9.92,9.85,9.92,△0.02,152,9.90,9.89,9.94,9.80
4,NaN,1414 東和,13:14,7.05,7.05,7.10,▽0.01,103,7.06,7.06,7.09,7.05

In [6]:
df_tmp[2].describe()

        選擇          買進          賣出          昨收
count  0.0   45.000000   45.000000   45.000000
mean   NaN   30.160444   30.286667   30.174667
std    NaN   63.693907   63.784349   63.526012
min    NaN    4.740000    5.150000    5.050000
25%    NaN    8.230000    8.330000    8.320000
50%    NaN   11.200000   11.250000   11.350000
75%    NaN   26.950000   27.050000   27.100000
max    NaN  401.500000  402.000000  400.000000