In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np
import webbrowser
from ipywidgets import interact
import sympy as sp

In [8]:
df_tmp=pd.read_html('https://tw.stock.yahoo.com/s/list.php?c=%AD%B9%AB%7E&rr=0.06800000%201574165733',encoding='big5')

In [9]:
df_tmp[2]

,選擇,股票代號,時間,成交,買進,賣出,漲跌,張數,昨收,開盤,最高,最低
0,NaN,1201 味全,14:30,25.10,25.05,25.10,△0.10,1061,25.00,25.05,25.20,24.80
1,NaN,1203 味王,13:12,26.85,26.85,26.90,0.00,21,26.85,26.90,27.05,26.80
2,NaN,1210 大成,14:30,40.35,40.35,40.40,△0.35,2474,40.00,40.00,40.65,40.00
3,NaN,1213 大飲,13:24,5.90,5.87,6.00,▽0.20,17,6.10,5.91,6.01,5.86
4,NaN,1215 卜蜂,14:30,64.70,64.60,64.70,△0.3,443,64.40,64.40,64.80,64.30
5,NaN,1216 統一,14:30,74.00,73.80,74.00,△0.1,6489,73.90,73.20,74.10,73.00
6,NaN,1217 愛之味,13:30,6.93,6.93,6.94,▽0.01,313,6.94,6.95,6.95,6.92
7,NaN,1218 泰山,14:30,22.30,22.20,22.30,△0.20,752,22.10,22.00,22.40,22.00
8,NaN,1219 福壽,13:09,17.90,17.80,17.90,△0.05,15,17.85,17.85,17.95,17.85
9,NaN,1220 台榮,13:30,10.65,10.65,10.70,△0.10,427,10.55,10.60,10.70,10.55
10,NaN,1225 福懋油,13:30,34.80,34.80,35.05,▽0.65,85,35.45,35.45,35.60,34.80
11,NaN,1227 佳格,14:30,62.60,62.30,62.60,▽0.2,577,62.80,61.70,62.60,61.70
12,NaN,1229 聯華,14:30,35.75,35.70,35.75,0.00,1049,35.75,35.70,35.80,35.55
13,NaN,1231 聯華食,14:30,40.70,40.70,40.75,△0.20,115,40.50,40.50,40.75,40.45
14,NaN,1232 大統益,13:30,123.50,123.50,124.00,▽0.5,31,124.00,124.00,125.00,123.50
15,NaN,1233 天仁,13:18,38.35,38.35,38.60,▽0.15,36,38.50,38.10,38.55,38.10
16,NaN,1234 黑松,13:30,32.50,32.50,32.60,△0.10,142,32.40,32.50,32.55,32.40
17,NaN,1235 興泰,13:30,26.10,26.10,26.60,△0.65,47,25.45,25.40,26.10,25.00
18,NaN,1236 宏亞,12:10,12.60,12.60,12.65,▽0.10,15,12.70,12.70,12.70,12.60
19,NaN,1256 鮮活果汁-KY,13:30,214.00,213.00,214.00,0.00,39,214.00,213.50,214.00,213.00
20,NaN,1702 南僑,13:30,49.80,49.80,49.90,▽0.20,158,50.00,50.00,50.00,49.80
21,NaN,1737 臺鹽,14:30,31.15,31.15,31.20,▽0.45,1188,31.60,31.60,31.60,30.95

In [10]:
df_tmp[2].head()

,選擇,股票代號,時間,成交,買進,賣出,漲跌,張數,昨收,開盤,最高,最低
0,NaN,1201 味全,14:30,25.10,25.05,25.1,△0.10,1061,25.00,25.05,25.20,24.80
1,NaN,1203 味王,13:12,26.85,26.85,26.9,0.00,21,26.85,26.90,27.05,26.80
2,NaN,1210 大成,14:30,40.35,40.35,40.4,△0.35,2474,40.00,40.00,40.65,40.00
3,NaN,1213 大飲,13:24,5.90,5.87,6.0,▽0.20,17,6.10,5.91,6.01,5.86
4,NaN,1215 卜蜂,14:30,64.70,64.60,64.7,△0.3,443,64.40,64.40,64.80,64.30

In [11]:
df_tmp[2].describe()

,選擇,成交,買進,賣出,張數,昨收,開盤,最高,最低
count,0.0,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000
mean,NaN,45.296818,45.209091,45.392727,704.272727,45.310909,45.182273,45.502727,44.996818
std,NaN,46.004851,45.825048,46.020115,1420.948482,46.043919,45.925793,46.093547,45.831720
min,NaN,5.900000,5.870000,6.000000,15.000000,6.100000,5.910000,6.010000,5.860000
25%,NaN,23.000000,22.912500,23.000000,36.750000,22.825000,22.762500,23.100000,22.700000
50%,NaN,33.650000,33.650000,33.825000,150.000000,33.925000,33.975000,34.075000,33.600000
75%,NaN,47.525000,47.525000,47.612500,708.250000,47.625000,47.625000,47.687500,47.462500
max,NaN,214.000000,213.000000,214.000000,6489.000000,214.000000,213.500000,214.000000,213.000000

In [12]:
df_tmp[2][df_tmp[2].最高>300].sort_values(by="最高",ascending=False)

Empty DataFrame
Columns: [選擇, 股票代號, 時間, 成交, 買進, 賣出, 漲跌, 張數, 昨收, 開盤, 最高, 最低]
Index: []