In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [8]:
df=pd.read_html('https://housing.kcg.gov.tw/LFA/LFA03/LFA03007004.jsp')

In [11]:
df[5].head()

,時間,時間.1,旗津區,旗津區.1,小港區,小港區.1,鳳山區,鳳山區.1,鳥松區,鳥松區.1,仁武區,仁武區.1
0,年度,NaN,人口密度 (人/平方公里),家戶密度 (戶/平方公里),人口密度 (人/平方公里),家戶密度 (戶/平方公里),人口密度 (人/平方公里),家戶密度 (戶/平方公里),人口密度 (人/平方公里),家戶密度 (戶/平方公里),人口密度(人/平方公里),家戶密度(戶/平方公里)
1,105,NaN,19756,7574,3926,1677,13347,5155,1792,727,2311,876
2,106,NaN,19672,7597,3944,1699,13397,5226,1800,740,2356,903
3,107,NaN,19542,7587,3953,1714,13420,5281,1802,748,2406,933
4,108,NaN,19326,7588,3957,1726,13446,5332,1820,766,2461,967